%YAML:1.2
geometry_path: "./cube1.obj"
geometry_unit_in_meter: 1
geometry_counterclockwise: 1
geometry_enable_culling: 0
geometry2body_pose: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [ 1., 0, 0, -0.03,
          0,  1., 0, -0.03,
          0,  0, 1., -0.06,
          0, 0, 0, 1. ]