/aruco_node:
  ros__parameters:
    marker_size: 0.055
    aruco_dictionary_id: DICT_5X5_250
    image_topic_eyeinhand: /camera/D455/color/image_raw
    camera_info_topic_eyeinhand: /camera/D455/color/camera_info
    image_topic_eyetohand: /camera/D455/color/image_raw
    camera_info_topic_eyetohand: /camera/D455/color/camera_info